### ISSUE TITLE
Software checklist/questions

### ISSUE THREAD

**Issue by dcwhite** [SCIInstitute/UncertainSCI#1]
- [x] Slack/Github integration. Send to separate channel?
- [x] Github action build. What tests to run?
- [x] Python version constraints?
- [x] Need a list of dependencies with versions 
- [x] Branching model and team/collaborator permissions
